### ISSUE TITLE
IDE online v2

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/website-wollok-ts#45]
Acabamos de liberar la primera versión, dejo ideas para una segunda iteración:

- [ ] guardar en el localStorage el programa, recuperarlo de ahí o crear el programita como seed
- [ ] mostrar un badgecito y decir que el REPL quedó desactualizado cuando cambie
- [ ] mostrar light vs. dark para zoom in/out
- [ ] ver si se puede poner un document.getElementsByTagName('html')[0].onChange
- [ ] migrar a wollok-ts y wollok-web-tools el código repetido para el diagrama dinámico y el REPL
- [ ] que puedas cargar un archivo
- [ ] que puedas cargar un proyecto (más heavy, tiene que eliminar los imports y hacer un join de los archivos wlk
- [ ] que puedas resizear los contenedores: diagrama dinámico o evaluador de expresiones

**Comment by PalumboN** [comment]
> que puedas cargar un proyecto (más heavy, tiene que eliminar los imports y hacer un join de los archivos wlk

Mmmm para tener accesso en la consola, no? Se podría crear un archivo `main.wlk` importando todos los otros...

Como cargar un archivo o proyecto lo hacía el run client:
- Desde local: https://github.com/uqbar-project/wollok-run-client/blob/master/src/components/filesSelector/LocalSelector.tsx
- Desde github haciendo cosas locas: https://github.com/uqbar-project/wollok-run-client/blob/master/src/components/filesSelector/GitSelector.tsx


----

Por otro lado, agrego a la lista:

- [ ] Poder "scrollear" para arriba en la consola para ver los resultados anteriores

**Comment by fdodino** [comment]
Listo el pollo! Cierro el issue
